version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      sunshine:
        patterns:
          - "*sunshine*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
